// <auto-generated />
using System;
using Gov.Structure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gov.Structure.Migrations
{
    [DbContext(typeof(GovContext))]
    [Migration("20200503175617_GovMigration")]
    partial class GovMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gov.Core.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("Gov.Core.Coalizione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Coalizione");
                });

            modelBuilder.Entity("Gov.Core.Dicastero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataGiuramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSfiducia")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GovernoId")
                        .HasColumnType("int");

                    b.Property<int?>("MinisteroId")
                        .HasColumnType("int");

                    b.Property<int?>("MinistroId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GovernoId");

                    b.HasIndex("MinisteroId");

                    b.HasIndex("MinistroId");

                    b.ToTable("Dicastero");
                });

            modelBuilder.Entity("Gov.Core.Governo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFiducia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataIncarico")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRevoca")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFiducia")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegislaturaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMinisteri")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMinisteriSenzaPortafogio")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVotiCamera")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVotiSenato")
                        .HasColumnType("int");

                    b.Property<int?>("PremierId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LegislaturaId");

                    b.HasIndex("PremierId");

                    b.ToTable("Governo");
                });

            modelBuilder.Entity("Gov.Core.Legislatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("SenatoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("SenatoId");

                    b.ToTable("Legislatura");
                });

            modelBuilder.Entity("Gov.Core.Militanza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInizio")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MinistroId")
                        .HasColumnType("int");

                    b.Property<int?>("PartitoId")
                        .HasColumnType("int");

                    b.Property<int?>("PremierId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MinistroId");

                    b.HasIndex("PartitoId");

                    b.HasIndex("PremierId");

                    b.ToTable("Militanza");
                });

            modelBuilder.Entity("Gov.Core.Ministero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCessazione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIstituzione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("IsSenzaPortafoglio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ministero");
                });

            modelBuilder.Entity("Gov.Core.Ministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ministro");
                });

            modelBuilder.Entity("Gov.Core.Partito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<int?>("CoalizioneId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int?>("SenatoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("CoalizioneId");

                    b.HasIndex("SenatoId");

                    b.ToTable("Partito");
                });

            modelBuilder.Entity("Gov.Core.Premier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Premier");
                });

            modelBuilder.Entity("Gov.Core.Senato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Senato");
                });

            modelBuilder.Entity("Gov.Core.Dicastero", b =>
                {
                    b.HasOne("Gov.Core.Governo", null)
                        .WithMany("Dicasteri")
                        .HasForeignKey("GovernoId");

                    b.HasOne("Gov.Core.Ministero", "Ministero")
                        .WithMany()
                        .HasForeignKey("MinisteroId");

                    b.HasOne("Gov.Core.Ministro", "Ministro")
                        .WithMany()
                        .HasForeignKey("MinistroId");
                });

            modelBuilder.Entity("Gov.Core.Governo", b =>
                {
                    b.HasOne("Gov.Core.Legislatura", "Legislatura")
                        .WithMany()
                        .HasForeignKey("LegislaturaId");

                    b.HasOne("Gov.Core.Premier", "Premier")
                        .WithMany()
                        .HasForeignKey("PremierId");
                });

            modelBuilder.Entity("Gov.Core.Legislatura", b =>
                {
                    b.HasOne("Gov.Core.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("Gov.Core.Senato", "Senato")
                        .WithMany()
                        .HasForeignKey("SenatoId");
                });

            modelBuilder.Entity("Gov.Core.Militanza", b =>
                {
                    b.HasOne("Gov.Core.Ministro", null)
                        .WithMany("Militanze")
                        .HasForeignKey("MinistroId");

                    b.HasOne("Gov.Core.Partito", "Partito")
                        .WithMany()
                        .HasForeignKey("PartitoId");

                    b.HasOne("Gov.Core.Premier", null)
                        .WithMany("Militanze")
                        .HasForeignKey("PremierId");
                });

            modelBuilder.Entity("Gov.Core.Partito", b =>
                {
                    b.HasOne("Gov.Core.Camera", null)
                        .WithMany("Partiti")
                        .HasForeignKey("CameraId");

                    b.HasOne("Gov.Core.Coalizione", "Coalizione")
                        .WithMany()
                        .HasForeignKey("CoalizioneId");

                    b.HasOne("Gov.Core.Senato", null)
                        .WithMany("Partiti")
                        .HasForeignKey("SenatoId");
                });
#pragma warning restore 612, 618
        }
    }
}
