// <auto-generated />
using System;
using Gov.Structure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gov.Structure.Migrations
{
    [DbContext(typeof(GovContext))]
    partial class GovContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Gov.Core.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Camera");
                });

            modelBuilder.Entity("Gov.Core.Coalizione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Coalizione");
                });

            modelBuilder.Entity("Gov.Core.Dicastero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataGiuramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSfiducia")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GovernoId")
                        .HasColumnType("int");

                    b.Property<int?>("MinisteroId")
                        .HasColumnType("int");

                    b.Property<int?>("MinistroId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GovernoId");

                    b.HasIndex("MinisteroId");

                    b.HasIndex("MinistroId");

                    b.ToTable("Dicastero");
                });

            modelBuilder.Entity("Gov.Core.Entity.Contenuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentuoCard")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaginaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<int>("TipoContenutoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaginaId");

                    b.HasIndex("TipoContenutoId");

                    b.ToTable("Contenuto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentuoCard = "Da questa pagina è possibile registrare un nuovo Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(4099),
                            PaginaId = 1,
                            Tipo = "Testo",
                            TipoContenutoId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ContentuoCard = "user-secret",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5276),
                            PaginaId = 1,
                            Tipo = "Icona",
                            TipoContenutoId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ContentuoCard = "/premier/inserimento",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5312),
                            PaginaId = 1,
                            Tipo = "Link",
                            TipoContenutoId = 3,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ContentuoCard = "Premier Inserimento",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5315),
                            PaginaId = 1,
                            Tipo = "Header",
                            TipoContenutoId = 4,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ContentuoCard = "Da questa pagina è possibile modificare un Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5319),
                            PaginaId = 2,
                            Tipo = "Testo",
                            TipoContenutoId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ContentuoCard = "user-secret",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5323),
                            PaginaId = 2,
                            Tipo = "Icona",
                            TipoContenutoId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ContentuoCard = "/premier/modifica",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5326),
                            PaginaId = 2,
                            Tipo = "Link",
                            TipoContenutoId = 3,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ContentuoCard = "Premier Modifica",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5330),
                            PaginaId = 2,
                            Tipo = "Header",
                            TipoContenutoId = 4,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ContentuoCard = "Da questa pagina è possibile visualizzare i Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5334),
                            PaginaId = 3,
                            Tipo = "Testo",
                            TipoContenutoId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            ContentuoCard = "user-secret",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5337),
                            PaginaId = 3,
                            Tipo = "Icona",
                            TipoContenutoId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            ContentuoCard = "/premier/visualizza",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5340),
                            PaginaId = 3,
                            Tipo = "Link",
                            TipoContenutoId = 3,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            ContentuoCard = "Premier Visualizzazione",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5344),
                            PaginaId = 3,
                            Tipo = "Header",
                            TipoContenutoId = 4,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            ContentuoCard = "Premier Visualizzazione",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5347),
                            PaginaId = 3,
                            Tipo = "Header",
                            TipoContenutoId = 4,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            ContentuoCard = "Da questa pagina è possibile gestire gli Utenti",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5351),
                            PaginaId = 8,
                            Tipo = "Testo",
                            TipoContenutoId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            ContentuoCard = "ApplicationUser",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5354),
                            PaginaId = 8,
                            Tipo = "Icona",
                            TipoContenutoId = 2,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            ContentuoCard = "/account/index",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5357),
                            PaginaId = 8,
                            Tipo = "Link",
                            TipoContenutoId = 3,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            ContentuoCard = "Gestione Utenti",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(5361),
                            PaginaId = 8,
                            Tipo = "Header",
                            TipoContenutoId = 4,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Gov.Core.Entity.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Pagina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(6545),
                            Denominazione = "Inserimento Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(7949),
                            Denominazione = "Modifica Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(8541),
                            Denominazione = "Visualizzazione Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Codice = "User",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(9079),
                            Denominazione = "Indice Gestione Utenti",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 57, DateTimeKind.Local).AddTicks(9621),
                            Denominazione = "Inserimento Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(121),
                            Denominazione = "Modifica Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Codice = "Premier",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(612),
                            Denominazione = "Visualizzazione Premier",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Codice = "User",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(1096),
                            Denominazione = "Gestione Utenti",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Codice = "User",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(1571),
                            Denominazione = "Registrazione Utenti",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Codice = "User",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(2050),
                            Denominazione = "Mio Profilo",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Codice = "User",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(2526),
                            Denominazione = "Mio Profilo",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Gov.Core.Entity.TipoContenuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TipoContenuto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codice = "Testo",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 59, DateTimeKind.Local).AddTicks(2018),
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Codice = "Icona",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 59, DateTimeKind.Local).AddTicks(2045),
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Codice = "Link",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 59, DateTimeKind.Local).AddTicks(2054),
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Codice = "Header",
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 59, DateTimeKind.Local).AddTicks(2059),
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Gov.Core.Entity.VoceMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icona")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Voce")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VoceMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(5185),
                            Icona = "user-secret",
                            Link = "/partito/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Premier"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(6382),
                            Icona = "history",
                            Link = "/governo/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Governo"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(6906),
                            Icona = "receipt",
                            Link = "/dicastero/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Dicastero"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(7426),
                            Icona = "university",
                            Link = "/partito/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Partito"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(7909),
                            Icona = "user",
                            Link = "/account/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Partito"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(8411),
                            Icona = "user-secret",
                            Link = "/partito/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Premier"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(8917),
                            Icona = "history",
                            Link = "/governo/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Governo"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(9393),
                            Icona = "receipt",
                            Link = "/dicastero/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Dicastero"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 58, DateTimeKind.Local).AddTicks(9862),
                            Icona = "university",
                            Link = "/partito/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Partito"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedBy = "Caricamento",
                            CreatedDate = new DateTime(2020, 5, 25, 22, 41, 19, 59, DateTimeKind.Local).AddTicks(332),
                            Icona = "user",
                            Link = "/account/index",
                            RoleId = 1,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Voce = "Partito"
                        });
                });

            modelBuilder.Entity("Gov.Core.Governo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFiducia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataIncarico")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRevoca")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFiducia")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LegislaturaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMinisteri")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMinisteriSenzaPortafogio")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVotiCamera")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVotiSenato")
                        .HasColumnType("int");

                    b.Property<int?>("PremierId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LegislaturaId");

                    b.HasIndex("PremierId");

                    b.ToTable("Governo");
                });

            modelBuilder.Entity("Gov.Core.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "bf65f6fb-636e-4ba1-a750-15b3fe27a06b",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "b1828072-06b1-4da2-aa7a-5f15f07c8da3",
                            Name = "user",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("Gov.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cognome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CustomTag")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sesso")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CodiceFiscale = "RBRNCL74P16H501C",
                            Cognome = "Admin",
                            Email = "agnew74@gmail.com",
                            EmailConfirmed = false,
                            LastModified = new DateTime(2020, 5, 25, 22, 41, 19, 56, DateTimeKind.Local).AddTicks(3048),
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "agnew74@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAECKpktWazyRDsxcGryPGbufMEjlButvirZr11PzV+rZcdcj1j2v7bv9rXb8InXvAgw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Sesso = "Maschio",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Gov.Core.Identity.UserAudit", b =>
                {
                    b.Property<int>("UserAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuditEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserAuditId");

                    b.ToTable("UserAudit");
                });

            modelBuilder.Entity("Gov.Core.Legislatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("SenatoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("SenatoId");

                    b.ToTable("Legislatura");
                });

            modelBuilder.Entity("Gov.Core.Militanza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInizio")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MinistroId")
                        .HasColumnType("int");

                    b.Property<int?>("PartitoId")
                        .HasColumnType("int");

                    b.Property<int?>("PremierId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MinistroId");

                    b.HasIndex("PartitoId");

                    b.HasIndex("PremierId");

                    b.ToTable("Militanza");
                });

            modelBuilder.Entity("Gov.Core.Ministero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCessazione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIstituzione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("IsSenzaPortafoglio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ministero");
                });

            modelBuilder.Entity("Gov.Core.Ministro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Ministro");
                });

            modelBuilder.Entity("Gov.Core.Partito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CameraId")
                        .HasColumnType("int");

                    b.Property<int?>("CoalizioneId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int?>("SenatoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("CoalizioneId");

                    b.HasIndex("SenatoId");

                    b.ToTable("Partito");
                });

            modelBuilder.Entity("Gov.Core.Premier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Premier");
                });

            modelBuilder.Entity("Gov.Core.Senato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFine")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Senato");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRoleClaim<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserClaim<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(128) CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserLogin<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserToken<int>");
                });

            modelBuilder.Entity("Gov.Core.Identity.Roleclaims", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>");

                    b.ToTable("Roleclaims");

                    b.HasDiscriminator().HasValue("Roleclaims");
                });

            modelBuilder.Entity("Gov.Core.Identity.Userclaims", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserClaims");

                    b.HasDiscriminator().HasValue("Userclaims");
                });

            modelBuilder.Entity("Gov.Core.Identity.Userlogins", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserLogins");

                    b.HasDiscriminator().HasValue("Userlogins");
                });

            modelBuilder.Entity("Gov.Core.Identity.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.HasIndex("ApplicationUserId");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Gov.Core.Identity.Usertokens", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserToken<int>");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserTokens");

                    b.HasDiscriminator().HasValue("Usertokens");
                });

            modelBuilder.Entity("Gov.Core.Dicastero", b =>
                {
                    b.HasOne("Gov.Core.Governo", null)
                        .WithMany("Dicasteri")
                        .HasForeignKey("GovernoId");

                    b.HasOne("Gov.Core.Ministero", "Ministero")
                        .WithMany()
                        .HasForeignKey("MinisteroId");

                    b.HasOne("Gov.Core.Ministro", "Ministro")
                        .WithMany()
                        .HasForeignKey("MinistroId");
                });

            modelBuilder.Entity("Gov.Core.Entity.Contenuto", b =>
                {
                    b.HasOne("Gov.Core.Entity.Pagina", "Pagina")
                        .WithMany()
                        .HasForeignKey("PaginaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gov.Core.Entity.TipoContenuto", "TipoConenuto")
                        .WithMany()
                        .HasForeignKey("TipoContenutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gov.Core.Entity.Pagina", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationRole", "Role")
                        .WithMany("Pagine")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gov.Core.Entity.VoceMenu", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationRole", "Role")
                        .WithMany("VociMenu")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gov.Core.Governo", b =>
                {
                    b.HasOne("Gov.Core.Legislatura", "Legislatura")
                        .WithMany()
                        .HasForeignKey("LegislaturaId");

                    b.HasOne("Gov.Core.Premier", "Premier")
                        .WithMany()
                        .HasForeignKey("PremierId");
                });

            modelBuilder.Entity("Gov.Core.Identity.ApplicationRole", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Gov.Core.Identity.UserAudit", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserAuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gov.Core.Legislatura", b =>
                {
                    b.HasOne("Gov.Core.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId");

                    b.HasOne("Gov.Core.Senato", "Senato")
                        .WithMany()
                        .HasForeignKey("SenatoId");
                });

            modelBuilder.Entity("Gov.Core.Militanza", b =>
                {
                    b.HasOne("Gov.Core.Ministro", null)
                        .WithMany("Militanze")
                        .HasForeignKey("MinistroId");

                    b.HasOne("Gov.Core.Partito", "Partito")
                        .WithMany()
                        .HasForeignKey("PartitoId");

                    b.HasOne("Gov.Core.Premier", null)
                        .WithMany("Militanze")
                        .HasForeignKey("PremierId");
                });

            modelBuilder.Entity("Gov.Core.Partito", b =>
                {
                    b.HasOne("Gov.Core.Camera", null)
                        .WithMany("Partiti")
                        .HasForeignKey("CameraId");

                    b.HasOne("Gov.Core.Coalizione", "Coalizione")
                        .WithMany()
                        .HasForeignKey("CoalizioneId");

                    b.HasOne("Gov.Core.Senato", null)
                        .WithMany("Partiti")
                        .HasForeignKey("SenatoId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gov.Core.Identity.Userclaims", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany("Userclaims")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Gov.Core.Identity.Userlogins", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany("Userlogins")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Gov.Core.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Gov.Core.Identity.Usertokens", b =>
                {
                    b.HasOne("Gov.Core.Identity.ApplicationUser", null)
                        .WithMany("Usertokens")
                        .HasForeignKey("ApplicationUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
